VPATH = /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/./test/malloc_wx
include /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/Makefile.config
include ${VPATH}/Makefile.generic
