VPATH = /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/.
include /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/Makefile.config
include ${VPATH}/Makefile.generic
