VPATH = /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/./doc/manual
include /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/Makefile.config
include ${VPATH}/Makefile.generic
