
steps:
  - group: "Build"
    notify:
      - github_commit_status:
          context: "Build"
    steps:
      - label: "Launch build jobs"
        commands: |
          echo "Launch Linux build jobs."
          echo "Launch macOS build jobs:"
          echo "Launch Windows build jobs:"

  - group: "Test"
    notify:
      - github_commit_status:
          context: "Test"
    steps:
      - label: "Launch test jobs"
        commands: |
          echo "Launch Linux test jobs."
          echo "Launch macOS test jobs:"
          echo "Launch Windows test jobs:"
