
steps:
  - label: "Check if run pipelines"
    key: "check-diff"
    plugins:
      # https://github.com/buildkite-plugins/monorepo-diff-buildkite-plugin
      - monorepo-diff#v1.4.0:
          watch:
            # This match will catch all files that will trigger a CI run
            - path: "**/*"
              skip_path: 
                - '.devcontainer/'
                - '.github/'
                # NOTE: '.buildkite-external-version' is a part of Buildkite CI
                - '.clang-format'
                - '.clangd'
                - '.codecov.yml'
                - '.devcontainer'
                - '.git-blame-ignore-revs'
                - '.gitattributes'
                - '.github'
                - '.gitignore'
                - '.mailmap'
                - 'AGENTS.md'
                - 'CITATION.bib'
                - 'CITATION.cff'
                - 'CLAUDE.md'
                - 'CONTRIBUTING.md'
                # NOTE: 'HISTORY.md' is used in docs
                - 'julia.spdx.json'
                - 'LICENSE.md'
                # NOTE: 'NEWS.md' is used in docs
                - 'README.md'
                - 'THIRDPARTY.md'
                - 'typos.toml'
              config:
                command: "echo run-ci=true"

  - label: ":hammer: Build"
    command: "echo 1"
    key: build
    depends_on: check-diff

  - label: ":test_tube: Test"
    command: "echo 2"
    key: test
    depends_on: build
