VPATH = /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/./test/call_suite
include /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/Makefile.config
include ${VPATH}/Makefile.generic
