VPATH = /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/./test/suite_x86win32std
include /home/chenningcong/Documents/Code/StaticCompiler/julia/src/dyncall/Makefile.config
include ${VPATH}/Makefile.generic
